/** Valores persistidos em `icon_key` (kebab-case ou nome export Lucide). */
export const DEVELOPED_PLATFORM_ICON_OPTIONS = [
  { value: 'cloud-sun', label: 'Clima / dados' },
  { value: 'wrench', label: 'Ferramentas' },
  { value: 'globe', label: 'Web / global' },
  { value: 'layout-grid', label: 'Grade / apps' },
  { value: 'layers', label: 'Camadas' },
  { value: 'cpu', label: 'Computação' },
  { value: 'server', label: 'Servidor' },
  { value: 'database', label: 'Base de dados' },
  { value: 'network', label: 'Rede' },
  { value: 'hard-drive', label: 'Armazenamento' },
  { value: 'monitor', label: 'Monitor / UI' },
  { value: 'cloud-cog', label: 'Nuvem / serviços' },
  { value: 'bar-chart-3', label: 'Gráficos / métricas' },
  { value: 'line-chart', label: 'Séries temporais' },
  { value: 'activity', label: 'Atividade / sinais' },
  { value: 'gauge', label: 'Desempenho' },
  { value: 'brain', label: 'IA / modelos' },
  { value: 'bot', label: 'Automação / agente' },
  { value: 'code-2', label: 'Código / dev' },
  { value: 'workflow', label: 'Pipeline / fluxo' },
  { value: 'sparkles', label: 'Destaque / inovação' },
  { value: 'shield', label: 'Segurança' },
  { value: 'zap', label: 'Energia / rápido' },
  { value: 'satellite', label: 'Sensor / satélite' },
  { value: 'radar', label: 'Radar / detecção' },
  { value: 'telescope', label: 'Observação / pesquisa' },
  { value: 'flask-conical', label: 'Laboratório / experimento' },
  { value: 'map', label: 'Mapa / geo' },
  { value: 'earth', label: 'Planeta / clima global' },
  { value: 'tablet-smartphone', label: 'Mobile / multiplataforma' },
  { value: 'microchip', label: 'Hardware / chip' },
] as const
